#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKhachSanVui
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Quanlykhachsan2")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertchucvu(chucvu instance);
    partial void Updatechucvu(chucvu instance);
    partial void Deletechucvu(chucvu instance);
    partial void Insertkhachhang(khachhang instance);
    partial void Updatekhachhang(khachhang instance);
    partial void Deletekhachhang(khachhang instance);
    partial void Insertnguoidung(nguoidung instance);
    partial void Updatenguoidung(nguoidung instance);
    partial void Deletenguoidung(nguoidung instance);
    partial void Insertphong(phong instance);
    partial void Updatephong(phong instance);
    partial void Deletephong(phong instance);
    partial void Inserttinhtrang(tinhtrang instance);
    partial void Updatetinhtrang(tinhtrang instance);
    partial void Deletetinhtrang(tinhtrang instance);
    partial void Insertloaiphong(loaiphong instance);
    partial void Updateloaiphong(loaiphong instance);
    partial void Deleteloaiphong(loaiphong instance);
    partial void Insertnhanvien(nhanvien instance);
    partial void Updatenhanvien(nhanvien instance);
    partial void Deletenhanvien(nhanvien instance);
    partial void Insertphieuthuephong(phieuthuephong instance);
    partial void Updatephieuthuephong(phieuthuephong instance);
    partial void Deletephieuthuephong(phieuthuephong instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::QLKhachSanVui.Properties.Settings.Default.Quanlykhachsan2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<chucvu> chucvus
		{
			get
			{
				return this.GetTable<chucvu>();
			}
		}
		
		public System.Data.Linq.Table<khachhang> khachhangs
		{
			get
			{
				return this.GetTable<khachhang>();
			}
		}
		
		public System.Data.Linq.Table<nguoidung> nguoidungs
		{
			get
			{
				return this.GetTable<nguoidung>();
			}
		}
		
		public System.Data.Linq.Table<phong> phongs
		{
			get
			{
				return this.GetTable<phong>();
			}
		}
		
		public System.Data.Linq.Table<tinhtrang> tinhtrangs
		{
			get
			{
				return this.GetTable<tinhtrang>();
			}
		}
		
		public System.Data.Linq.Table<loaiphong> loaiphongs
		{
			get
			{
				return this.GetTable<loaiphong>();
			}
		}
		
		public System.Data.Linq.Table<nhanvien> nhanviens
		{
			get
			{
				return this.GetTable<nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<phieuthuephong> phieuthuephongs
		{
			get
			{
				return this.GetTable<phieuthuephong>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themkh")]
		public int themkh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tenkh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cmnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh, tenkh, gioitinh, ngaysinh, cmnd, sdt, diachi, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.update_kh")]
		public int update_kh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tenkh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string cmnd, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ghichu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh, tenkh, gioitinh, ngaysinh, cmnd, sdt, diachi, ghichu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deletekh")]
		public int deletekh([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string makh)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), makh);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themloaiphong")]
		public int themloaiphong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maloai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string songuoi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maloai, songuoi, gia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suaLoaiPhong")]
		public int suaLoaiPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maloai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string songuoi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gia)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maloai, songuoi, gia);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.deleteLoaiPhong")]
		public int deleteLoaiPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maloai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maloai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themtinhtrang")]
		public int themtinhtrang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string matinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tentinhtrang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matinhtrang, tentinhtrang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suatinhtrang")]
		public int suatinhtrang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string matinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tentinhtrang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matinhtrang, tentinhtrang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoatinhtrang")]
		public int xoatinhtrang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string matinhtrang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matinhtrang);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themPhong")]
		public int themPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string matinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maloai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, matinhtrang, maloai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suaNhanVien")]
		public int suaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tennv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string luong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, tennv, gioitinh, ngaysinh, sdt, diachi, chucvu, luong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaNhanVien")]
		public int xoaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string manv)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themChucvu")]
		public int themChucvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string machucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenchucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hesoluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machucvu, tenchucvu, hesoluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suaChucvu")]
		public int suaChucvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string machucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tenchucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string hesoluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machucvu, tenchucvu, hesoluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaChucvu")]
		public int xoaChucvu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string machuvu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), machuvu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themNhanVien")]
		public int themNhanVien1([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string manv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string tennv, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string luong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string chucvu, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string tongluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), manv, tennv, gioitinh, ngaysinh, sdt, diachi, luong, chucvu, tongluong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.suaPhong")]
		public int suaPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string matinhtrang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maloai)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong, matinhtrang, maloai);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaPhong")]
		public int xoaPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maphong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maphong);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themDatPhong")]
		public int themDatPhong([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string matp, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string maphong, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string makh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string ngaythue, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string soluong)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), matp, maphong, makh, ngaythue, soluong);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.chucvu")]
	public partial class chucvu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _machucvu;
		
		private string _tenchucvu;
		
		private string _hesoluong;
		
		private EntitySet<nhanvien> _nhanviens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmachucvuChanging(string value);
    partial void OnmachucvuChanged();
    partial void OntenchucvuChanging(string value);
    partial void OntenchucvuChanged();
    partial void OnhesoluongChanging(string value);
    partial void OnhesoluongChanged();
    #endregion
		
		public chucvu()
		{
			this._nhanviens = new EntitySet<nhanvien>(new Action<nhanvien>(this.attach_nhanviens), new Action<nhanvien>(this.detach_nhanviens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machucvu", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string machucvu
		{
			get
			{
				return this._machucvu;
			}
			set
			{
				if ((this._machucvu != value))
				{
					this.OnmachucvuChanging(value);
					this.SendPropertyChanging();
					this._machucvu = value;
					this.SendPropertyChanged("machucvu");
					this.OnmachucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenchucvu", DbType="NVarChar(50)")]
		public string tenchucvu
		{
			get
			{
				return this._tenchucvu;
			}
			set
			{
				if ((this._tenchucvu != value))
				{
					this.OntenchucvuChanging(value);
					this.SendPropertyChanging();
					this._tenchucvu = value;
					this.SendPropertyChanged("tenchucvu");
					this.OntenchucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hesoluong", DbType="NVarChar(50)")]
		public string hesoluong
		{
			get
			{
				return this._hesoluong;
			}
			set
			{
				if ((this._hesoluong != value))
				{
					this.OnhesoluongChanging(value);
					this.SendPropertyChanging();
					this._hesoluong = value;
					this.SendPropertyChanged("hesoluong");
					this.OnhesoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chucvu_nhanvien", Storage="_nhanviens", ThisKey="machucvu", OtherKey="machucvu")]
		public EntitySet<nhanvien> nhanviens
		{
			get
			{
				return this._nhanviens;
			}
			set
			{
				this._nhanviens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.chucvu = this;
		}
		
		private void detach_nhanviens(nhanvien entity)
		{
			this.SendPropertyChanging();
			entity.chucvu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.khachhang")]
	public partial class khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _makh;
		
		private string _tenkh;
		
		private string _gioitinh;
		
		private string _ngaysinh;
		
		private string _cmnd;
		
		private string _sdt;
		
		private string _diachi;
		
		private string _ghichu;
		
		private EntitySet<phieuthuephong> _phieuthuephongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OntenkhChanging(string value);
    partial void OntenkhChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    partial void OncmndChanging(string value);
    partial void OncmndChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnghichuChanging(string value);
    partial void OnghichuChanged();
    #endregion
		
		public khachhang()
		{
			this._phieuthuephongs = new EntitySet<phieuthuephong>(new Action<phieuthuephong>(this.attach_phieuthuephongs), new Action<phieuthuephong>(this.detach_phieuthuephongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenkh", DbType="VarChar(50)")]
		public string tenkh
		{
			get
			{
				return this._tenkh;
			}
			set
			{
				if ((this._tenkh != value))
				{
					this.OntenkhChanging(value);
					this.SendPropertyChanging();
					this._tenkh = value;
					this.SendPropertyChanged("tenkh");
					this.OntenkhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="VarChar(50)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="VarChar(50)")]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cmnd", DbType="VarChar(50)")]
		public string cmnd
		{
			get
			{
				return this._cmnd;
			}
			set
			{
				if ((this._cmnd != value))
				{
					this.OncmndChanging(value);
					this.SendPropertyChanging();
					this._cmnd = value;
					this.SendPropertyChanged("cmnd");
					this.OncmndChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="VarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghichu", DbType="VarChar(50)")]
		public string ghichu
		{
			get
			{
				return this._ghichu;
			}
			set
			{
				if ((this._ghichu != value))
				{
					this.OnghichuChanging(value);
					this.SendPropertyChanging();
					this._ghichu = value;
					this.SendPropertyChanged("ghichu");
					this.OnghichuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_phieuthuephong", Storage="_phieuthuephongs", ThisKey="makh", OtherKey="makh")]
		public EntitySet<phieuthuephong> phieuthuephongs
		{
			get
			{
				return this._phieuthuephongs;
			}
			set
			{
				this._phieuthuephongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phieuthuephongs(phieuthuephong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = this;
		}
		
		private void detach_phieuthuephongs(phieuthuephong entity)
		{
			this.SendPropertyChanging();
			entity.khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nguoidung")]
	public partial class nguoidung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _taikhoan;
		
		private string _matkhau;
		
		private string _chucvu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OntaikhoanChanging(string value);
    partial void OntaikhoanChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnchucvuChanging(string value);
    partial void OnchucvuChanged();
    #endregion
		
		public nguoidung()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_taikhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string taikhoan
		{
			get
			{
				return this._taikhoan;
			}
			set
			{
				if ((this._taikhoan != value))
				{
					this.OntaikhoanChanging(value);
					this.SendPropertyChanging();
					this._taikhoan = value;
					this.SendPropertyChanged("taikhoan");
					this.OntaikhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="VarChar(50)")]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chucvu", DbType="VarChar(50)")]
		public string chucvu
		{
			get
			{
				return this._chucvu;
			}
			set
			{
				if ((this._chucvu != value))
				{
					this.OnchucvuChanging(value);
					this.SendPropertyChanging();
					this._chucvu = value;
					this.SendPropertyChanged("chucvu");
					this.OnchucvuChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phong")]
	public partial class phong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maphong;
		
		private string _matinhtrang;
		
		private string _maloai;
		
		private EntityRef<tinhtrang> _tinhtrang;
		
		private EntityRef<loaiphong> _loaiphong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnmatinhtrangChanging(string value);
    partial void OnmatinhtrangChanged();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    #endregion
		
		public phong()
		{
			this._tinhtrang = default(EntityRef<tinhtrang>);
			this._loaiphong = default(EntityRef<loaiphong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matinhtrang", DbType="VarChar(50)")]
		public string matinhtrang
		{
			get
			{
				return this._matinhtrang;
			}
			set
			{
				if ((this._matinhtrang != value))
				{
					if (this._tinhtrang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmatinhtrangChanging(value);
					this.SendPropertyChanging();
					this._matinhtrang = value;
					this.SendPropertyChanged("matinhtrang");
					this.OnmatinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="VarChar(50)")]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					if (this._loaiphong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tinhtrang_phong", Storage="_tinhtrang", ThisKey="matinhtrang", OtherKey="matinhtrang", IsForeignKey=true)]
		public tinhtrang tinhtrang
		{
			get
			{
				return this._tinhtrang.Entity;
			}
			set
			{
				tinhtrang previousValue = this._tinhtrang.Entity;
				if (((previousValue != value) 
							|| (this._tinhtrang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tinhtrang.Entity = null;
						previousValue.phongs.Remove(this);
					}
					this._tinhtrang.Entity = value;
					if ((value != null))
					{
						value.phongs.Add(this);
						this._matinhtrang = value.matinhtrang;
					}
					else
					{
						this._matinhtrang = default(string);
					}
					this.SendPropertyChanged("tinhtrang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_loaiphong", ThisKey="maloai", OtherKey="maloai", IsForeignKey=true)]
		public loaiphong loaiphong
		{
			get
			{
				return this._loaiphong.Entity;
			}
			set
			{
				loaiphong previousValue = this._loaiphong.Entity;
				if (((previousValue != value) 
							|| (this._loaiphong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._loaiphong.Entity = null;
						previousValue.phongs.Remove(this);
					}
					this._loaiphong.Entity = value;
					if ((value != null))
					{
						value.phongs.Add(this);
						this._maloai = value.maloai;
					}
					else
					{
						this._maloai = default(string);
					}
					this.SendPropertyChanged("loaiphong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tinhtrang")]
	public partial class tinhtrang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matinhtrang;
		
		private string _tentinhtrang;
		
		private EntitySet<phong> _phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatinhtrangChanging(string value);
    partial void OnmatinhtrangChanged();
    partial void OntentinhtrangChanging(string value);
    partial void OntentinhtrangChanged();
    #endregion
		
		public tinhtrang()
		{
			this._phongs = new EntitySet<phong>(new Action<phong>(this.attach_phongs), new Action<phong>(this.detach_phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matinhtrang", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matinhtrang
		{
			get
			{
				return this._matinhtrang;
			}
			set
			{
				if ((this._matinhtrang != value))
				{
					this.OnmatinhtrangChanging(value);
					this.SendPropertyChanging();
					this._matinhtrang = value;
					this.SendPropertyChanged("matinhtrang");
					this.OnmatinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tentinhtrang", DbType="NVarChar(50)")]
		public string tentinhtrang
		{
			get
			{
				return this._tentinhtrang;
			}
			set
			{
				if ((this._tentinhtrang != value))
				{
					this.OntentinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tentinhtrang = value;
					this.SendPropertyChanged("tentinhtrang");
					this.OntentinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tinhtrang_phong", Storage="_phongs", ThisKey="matinhtrang", OtherKey="matinhtrang")]
		public EntitySet<phong> phongs
		{
			get
			{
				return this._phongs;
			}
			set
			{
				this._phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.tinhtrang = this;
		}
		
		private void detach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.tinhtrang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.loaiphong")]
	public partial class loaiphong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _maloai;
		
		private string _songuoi;
		
		private string _gia;
		
		private EntitySet<phong> _phongs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaloaiChanging(string value);
    partial void OnmaloaiChanged();
    partial void OnsonguoiChanging(string value);
    partial void OnsonguoiChanged();
    partial void OngiaChanging(string value);
    partial void OngiaChanged();
    #endregion
		
		public loaiphong()
		{
			this._phongs = new EntitySet<phong>(new Action<phong>(this.attach_phongs), new Action<phong>(this.detach_phongs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maloai", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string maloai
		{
			get
			{
				return this._maloai;
			}
			set
			{
				if ((this._maloai != value))
				{
					this.OnmaloaiChanging(value);
					this.SendPropertyChanging();
					this._maloai = value;
					this.SendPropertyChanged("maloai");
					this.OnmaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoi", DbType="VarChar(50)")]
		public string songuoi
		{
			get
			{
				return this._songuoi;
			}
			set
			{
				if ((this._songuoi != value))
				{
					this.OnsonguoiChanging(value);
					this.SendPropertyChanging();
					this._songuoi = value;
					this.SendPropertyChanged("songuoi");
					this.OnsonguoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gia", DbType="VarChar(50)")]
		public string gia
		{
			get
			{
				return this._gia;
			}
			set
			{
				if ((this._gia != value))
				{
					this.OngiaChanging(value);
					this.SendPropertyChanging();
					this._gia = value;
					this.SendPropertyChanged("gia");
					this.OngiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="loaiphong_phong", Storage="_phongs", ThisKey="maloai", OtherKey="maloai")]
		public EntitySet<phong> phongs
		{
			get
			{
				return this._phongs;
			}
			set
			{
				this._phongs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = this;
		}
		
		private void detach_phongs(phong entity)
		{
			this.SendPropertyChanging();
			entity.loaiphong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.nhanvien")]
	public partial class nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _manv;
		
		private string _tennv;
		
		private string _gioitinh;
		
		private string _ngaysinh;
		
		private string _sdt;
		
		private string _diachi;
		
		private string _luong;
		
		private string _machucvu;
		
		private string _tongluong;
		
		private EntityRef<chucvu> _chucvu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmanvChanging(string value);
    partial void OnmanvChanged();
    partial void OntennvChanging(string value);
    partial void OntennvChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(string value);
    partial void OnngaysinhChanged();
    partial void OnsdtChanging(string value);
    partial void OnsdtChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnluongChanging(string value);
    partial void OnluongChanged();
    partial void OnmachucvuChanging(string value);
    partial void OnmachucvuChanged();
    partial void OntongluongChanging(string value);
    partial void OntongluongChanged();
    #endregion
		
		public nhanvien()
		{
			this._chucvu = default(EntityRef<chucvu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_manv", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string manv
		{
			get
			{
				return this._manv;
			}
			set
			{
				if ((this._manv != value))
				{
					this.OnmanvChanging(value);
					this.SendPropertyChanging();
					this._manv = value;
					this.SendPropertyChanged("manv");
					this.OnmanvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tennv", DbType="VarChar(50)")]
		public string tennv
		{
			get
			{
				return this._tennv;
			}
			set
			{
				if ((this._tennv != value))
				{
					this.OntennvChanging(value);
					this.SendPropertyChanging();
					this._tennv = value;
					this.SendPropertyChanged("tennv");
					this.OntennvChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="VarChar(50)")]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="VarChar(50)")]
		public string ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdt", DbType="VarChar(50)")]
		public string sdt
		{
			get
			{
				return this._sdt;
			}
			set
			{
				if ((this._sdt != value))
				{
					this.OnsdtChanging(value);
					this.SendPropertyChanging();
					this._sdt = value;
					this.SendPropertyChanged("sdt");
					this.OnsdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="VarChar(50)")]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong", DbType="VarChar(50)")]
		public string luong
		{
			get
			{
				return this._luong;
			}
			set
			{
				if ((this._luong != value))
				{
					this.OnluongChanging(value);
					this.SendPropertyChanging();
					this._luong = value;
					this.SendPropertyChanged("luong");
					this.OnluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machucvu", DbType="NVarChar(50)")]
		public string machucvu
		{
			get
			{
				return this._machucvu;
			}
			set
			{
				if ((this._machucvu != value))
				{
					if (this._chucvu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmachucvuChanging(value);
					this.SendPropertyChanging();
					this._machucvu = value;
					this.SendPropertyChanged("machucvu");
					this.OnmachucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongluong", DbType="NVarChar(50)")]
		public string tongluong
		{
			get
			{
				return this._tongluong;
			}
			set
			{
				if ((this._tongluong != value))
				{
					this.OntongluongChanging(value);
					this.SendPropertyChanging();
					this._tongluong = value;
					this.SendPropertyChanged("tongluong");
					this.OntongluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="chucvu_nhanvien", Storage="_chucvu", ThisKey="machucvu", OtherKey="machucvu", IsForeignKey=true)]
		public chucvu chucvu
		{
			get
			{
				return this._chucvu.Entity;
			}
			set
			{
				chucvu previousValue = this._chucvu.Entity;
				if (((previousValue != value) 
							|| (this._chucvu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._chucvu.Entity = null;
						previousValue.nhanviens.Remove(this);
					}
					this._chucvu.Entity = value;
					if ((value != null))
					{
						value.nhanviens.Add(this);
						this._machucvu = value.machucvu;
					}
					else
					{
						this._machucvu = default(string);
					}
					this.SendPropertyChanged("chucvu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.phieuthuephong")]
	public partial class phieuthuephong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _matp;
		
		private string _maphong;
		
		private string _makh;
		
		private string _ngaythue;
		
		private string _soluong;
		
		private EntityRef<khachhang> _khachhang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmatpChanging(string value);
    partial void OnmatpChanged();
    partial void OnmaphongChanging(string value);
    partial void OnmaphongChanged();
    partial void OnmakhChanging(string value);
    partial void OnmakhChanged();
    partial void OnngaythueChanging(string value);
    partial void OnngaythueChanged();
    partial void OnsoluongChanging(string value);
    partial void OnsoluongChanged();
    #endregion
		
		public phieuthuephong()
		{
			this._khachhang = default(EntityRef<khachhang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matp", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string matp
		{
			get
			{
				return this._matp;
			}
			set
			{
				if ((this._matp != value))
				{
					this.OnmatpChanging(value);
					this.SendPropertyChanging();
					this._matp = value;
					this.SendPropertyChanged("matp");
					this.OnmatpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maphong", DbType="VarChar(50)")]
		public string maphong
		{
			get
			{
				return this._maphong;
			}
			set
			{
				if ((this._maphong != value))
				{
					this.OnmaphongChanging(value);
					this.SendPropertyChanging();
					this._maphong = value;
					this.SendPropertyChanged("maphong");
					this.OnmaphongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_makh", DbType="VarChar(50)")]
		public string makh
		{
			get
			{
				return this._makh;
			}
			set
			{
				if ((this._makh != value))
				{
					if (this._khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmakhChanging(value);
					this.SendPropertyChanging();
					this._makh = value;
					this.SendPropertyChanged("makh");
					this.OnmakhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaythue", DbType="VarChar(50)")]
		public string ngaythue
		{
			get
			{
				return this._ngaythue;
			}
			set
			{
				if ((this._ngaythue != value))
				{
					this.OnngaythueChanging(value);
					this.SendPropertyChanging();
					this._ngaythue = value;
					this.SendPropertyChanged("ngaythue");
					this.OnngaythueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluong", DbType="VarChar(50)")]
		public string soluong
		{
			get
			{
				return this._soluong;
			}
			set
			{
				if ((this._soluong != value))
				{
					this.OnsoluongChanging(value);
					this.SendPropertyChanging();
					this._soluong = value;
					this.SendPropertyChanged("soluong");
					this.OnsoluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="khachhang_phieuthuephong", Storage="_khachhang", ThisKey="makh", OtherKey="makh", IsForeignKey=true)]
		public khachhang khachhang
		{
			get
			{
				return this._khachhang.Entity;
			}
			set
			{
				khachhang previousValue = this._khachhang.Entity;
				if (((previousValue != value) 
							|| (this._khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._khachhang.Entity = null;
						previousValue.phieuthuephongs.Remove(this);
					}
					this._khachhang.Entity = value;
					if ((value != null))
					{
						value.phieuthuephongs.Add(this);
						this._makh = value.makh;
					}
					else
					{
						this._makh = default(string);
					}
					this.SendPropertyChanged("khachhang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
